<?php

declare(strict_types=1);

namespace arthur\resourcepackloader\api\generator;

use arthur\resourcepackloader\api\manifest\Header;
use arthur\resourcepackloader\api\manifest\Manifest;
use arthur\resourcepackloader\api\manifest\Module;
use arthur\resourcepackloader\api\manifest\Version;
use pocketmine\plugin\PluginBase;
use Ramsey\Uuid\Uuid;

class SimpleResourcePack extends ResourcePackGenerator{

	public function __construct(PluginBase $plugin, Version $version){
		$manifest = new Manifest(
			new Header(
				"Auto generated by ResourcePackLoader.",
				"ResourcePackLoader",
				Uuid::uuid3(Uuid::NAMESPACE_DNS, "header")->toString(),
				$version
			),
			[
				new Module(
					"Auto generated by ResourcePackLoader.",
					Module::TYPE_RESOURCES,
					Uuid::uuid3(Uuid::NAMESPACE_DNS, "modules")->toString(),
					$version
				),
			]
		);
		parent::__construct($plugin, $manifest);
	}
}